USE [master]
GO

/****** Object:  Database [ScrumQueue]    Script Date: 02/09/2012 09:43:46 ******/
CREATE DATABASE [ScrumQueue] ON  PRIMARY 
( NAME = N'ScrumQueue', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\ScrumQueue.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ScrumQueue_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\ScrumQueue.ldf' , SIZE = 3840KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ScrumQueue] SET COMPATIBILITY_LEVEL = 90
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ScrumQueue].[dbo].[sp_fulltext_database] @action = 'disable'
end
GO

ALTER DATABASE [ScrumQueue] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ScrumQueue] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ScrumQueue] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ScrumQueue] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ScrumQueue] SET ARITHABORT OFF 
GO

ALTER DATABASE [ScrumQueue] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ScrumQueue] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ScrumQueue] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ScrumQueue] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ScrumQueue] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ScrumQueue] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ScrumQueue] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ScrumQueue] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ScrumQueue] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ScrumQueue] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ScrumQueue] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ScrumQueue] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ScrumQueue] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ScrumQueue] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ScrumQueue] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ScrumQueue] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ScrumQueue] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ScrumQueue] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ScrumQueue] SET  READ_WRITE 
GO

ALTER DATABASE [ScrumQueue] SET RECOVERY FULL 
GO

ALTER DATABASE [ScrumQueue] SET  MULTI_USER 
GO

ALTER DATABASE [ScrumQueue] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ScrumQueue] SET DB_CHAINING OFF 
GO


